language: node_js
node_js:
  - "9"
install:
  - npm install -g truffle solium
  - npm install -g ganache-cli
  - npm install
script:
  - solium --dir contracts/
  - truffle compile
  - truffle test
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
